controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\web\NotAcceptableHttpException;
use app\models\User;
use yii\bootstrap4\ActiveForm;
use app\models\UserLog;
use app\models\UserLogAction;
use app\components\PhpMessageSource;
use yii\helpers\Url;

class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'account',
                            'update-account',
                            'change-password',
                            'logout',
                            'verify-email',
                            'email-verification-form',
                            'send-verification-email',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => [
                            'login',
                            'validate-email',
                            'signup',
                            'password-reset-request',
                            'password-reset-form',
                            'password-reset-post',
                        ],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => [
                            'error',
                            'language',
                        ],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'password-reset-post' => ['post'],
                    'send-new-verification-email' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['code/list']);
        }

        $model = new LoginForm;
        $post = Yii::$app->request->post();
        
        if ($model->load($post) && $model->login()) {
            UserLog::create(UserLogAction::ACTION_LOGIN);
            Yii::$app->user->identity->setAccountLanguage();
            return $this->redirect(['code/list']);
        }
        
        if (Yii::$app->request->isPost) {
            $model->password = '';
            
            $user = User::findByUsername($model->username);
            if ($user === null) {
                UserLog::create(UserLogAction::ACTION_LOGIN_FAIL_EMAIL);
            } else {
                UserLog::create(UserLogAction::ACTION_LOGIN_FAIL_PASSWORD, $user->id);
            }
        }
        
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        UserLog::create(UserLogAction::ACTION_LOGOUT);
        Yii::$app->user->logout();
        return $this->goHome();
    }

    /**
     * Displays signup view
     *
     * @return Response|string
     */
    public function actionSignup()
    {
        $model = new User(['scenario' => User::SCENARIO_SIGNUP]);
        
        $languageId = User::getLanguageId(Yii::$app->session->get('lang'));
        if (!is_null($languageId)) {
            $model->language = $languageId;
        }
        $post = Yii::$app->request->post();
        
        if ($model->load($post) && $model->validate()) {
            $model->create();
            UserLog::create(UserLogAction::ACTION_SIGNUP, $model->id);
            Yii::$app->session->setFlash(
                'messageSuccess', Yii::t('app', 'SIGNUP_SUCCESS_MESSAGE'));
            return $this->redirect('login');
        }
        
        $model->password = '';
        $model->passwordConfirm = '';
        $languageList = User::getMappedLanguages();
        
        return $this->render('signup', [
            'model' => $model,
            'languageList' => $languageList,
        ]);
    }
    
    /**
     * Returns json response with email validation errors
     *
     * @return string
     */
    public function actionValidateEmail()
    {
        $model = new User;
        $model->scenario = User::SCENARIO_VALIDATE_EMAIL;
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            UserLog::create(UserLogAction::ACTION_SIGNUP_VALIDATE_EMAIL);
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }
   
    /**
     * Changes language and refreshes page.
     *
     * @param string $lang
     * @throws NotAcceptableHttpException
     * @return Response|string
     */
    public function actionLanguage($lang)
    {
        $languageId = User::getLanguageId($lang);
        if (is_null($languageId)) {
            throw new NotAcceptableHttpException(
                Yii::t('app', 'BAD_REQUEST_ARGUMENT'));
        }
        Yii::$app->session->set('lang', $lang);
        
        if (!Yii::$app->user->isGuest) {
            $user = Yii::$app->user->identity;
            $user->setScenario(User::SCENARIO_UPDATE);
            $user->language = $languageId;
            $user->save();
        }
        
        UserLog::create(UserLogAction::ACTION_CHANGE_LANGUAGE);
        
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    /**
     * Password reset request view
     *
     * @params string|null $email
     * @throws NotAcceptableHttpException
     * @return Response|string
     */
    public function actionPasswordResetRequest($email = null)
    {
        $model = new User(['scenario' => User::SCENARIO_PASSWORD_RESET_REQUEST]);
        
        if (!Yii::$app->request->isPost) {
            $myData = [
                'messages' => PhpMessageSource::getMessages('frontend'),
                'email' => base64_decode($email),
            ];

            return $this->render('password-reset-request', [
                'model' => $model,
                'myData' => json_encode($myData),
            ]);
        }
        
        if (!Yii::$app->request->isAjax) {
            throw new NotAcceptableHttpException(
                Yii::t('app', 'BAD_POST_REQUEST'));
        }
        
        $post = Yii::$app->request->post();
        
        if ($model->load($post)) {
            $model->validate();
        }
        
        if ($model->hasErrors()) {
            return json_encode([
                'message' => 'error',
                'errors' => $model->firstErrors['email'],
            ]);
        }
        
        if ($model->sendRecoveryEmail()) {
            $user = User::findByUsername($model->email);
            UserLog::create(UserLogAction::ACTION_PASSWORD_RESET_REQUEST, $user->id);
            
            Yii::$app->session->setFlash('tokenSent',
                Yii::t('app', 'PASSWORD_REQUEST_SENT_TEXT'));
            return json_encode([
                'message' => 'success',
            ]);
        }
        
        return json_encode([
            'message' => 'error',
        ]);
    }
    
    /**
     * Checks password reset token and shows password change form
     *
     * @return Response|string
     */
    public function actionPasswordResetForm($token)
    {
        $model = User::findByToken('password_reset_token', $token, true);
        $expired = is_null($model) ? null : $model->isTokenExpired('password_reset_token');
        
        if ($expired === null) {
            Yii::$app->session->setFlash('errorMessage',
                Yii::t('app', 'ERROR_MESSAGE_INVALID_TOKEN'));
            return $this->redirect(['/site/message']);
        }
        
        if ($expired) {
            Yii::$app->session->setFlash('errorMessage',
                Yii::t('app', 'ERROR_MESSAGE_EXPIRED_TOKEN'));
            return $this->redirect(['/site/message']);
        }

        $model->setScenario(User::SCENARIO_SECURITY);
        $model->password_reset_token = Yii::$app->security
            ->generateRandomString();
        $model->save();
        
        $model->setScenario(User::SCENARIO_PASSWORD_RESET);
        
        $model->setAccountLanguage();
        
        return $this->render('password-reset', [
            'model' => $model,
            'key' => Yii::$app->security->maskToken($model->password_reset_token),
        ]);
    }

    /**
     * Password reset request view
     *
     * @return Response|string
     */
    public function actionPasswordResetPost()
    {        
        $post = Yii::$app->request->post();
        $token = Yii::$app->request->post('tag', '');
        
        $model = User::findByToken('password_reset_token', $token, true);
        
        if ($model === null) {
            Yii::$app->session->setFlash('errorMessage',
                Yii::t('app', 'INVALID_REQUEST'));
            return $this->redirect(['/site/message']);
        }
        
        $model->setScenario(User::SCENARIO_PASSWORD_RESET);
        $model->password_reset_token = null;
        
        if ($model->load($post) && $model->validate()) {

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use app\widgets\Alert;
use yii\helpers\Html;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;
use yii\helpers\Url;
use kartik\icons\Icon;
use app\components\Util;

AppAsset::register($this);
Icon::map($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?php echo Html::csrfMetaTags(); ?>
    <?php $this->registerCsrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <link href="https://fonts.googleapis.com/css?family=Open+Sans&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Poppins&display=swap" rel="stylesheet">
    <?php $this->head() ?>
</head>
<body>
<?php $this->beginBody() ; ?>
    
<div id="app" class="<?php echo Util::isFullHeight($this) ? 'layout-flex-column' : ''; ?>">

<nav class="site-header navbar navbar-expand-lg navbar-light bg-light border-bottom px-sm-3">
  <div class="container">
    <a class="site-navbar-brand navbar-brand" href="<?php echo Yii::$app->homeUrl; ?>"
       >My <span class="site-navbar-brand-code">{Code}</span> Base</a>
    <button class="navbar-toggler" 
        type="button" data-toggle="collapse" 
        data-target="#navbarSupportedContent" 
        aria-controls="navbarSupportedContent" 
        aria-expanded="false" 
        aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="site-nav navbar-nav mr-auto">
        <li class="site-nav-item nav-item<?php echo Util::getMenuActive($this, 'site/index'); ?>">
          <a class="nav-link" href="<?php echo Yii::$app->homeUrl; ?>"><?php echo Yii::t('app', 'MENU_HOME'); ?></a>
        </li>
        <li class="site-nav-item nav-item<?php echo Util::getMenuActive($this, 'site/contact'); ?>">
            <?php echo Html::a(
                Yii::t('app', 'MENU_CONTACT'), 
                Url::to(['site/contact']),
                [
                    'class' => 'nav-link',
                ]
            ); ?>
        </li>
        
        <?php if (!Yii::$app->user->isGuest) { ?>
            <li class="site-nav-item nav-item<?php echo Util::getMenuActive($this, 'code/list'); ?>">
                <?php echo Html::a(
                    Yii::t('app', 'MENU_CODE'), 
                    Url::to(['code/list']),
                    [
                        'class' => 'nav-link',
                    ]
                ); ?>
            </li>
        <?php } ?>
        
      </ul>
        <ul class="site-nav site-nav-right navbar-nav">
          <?php if (Yii::$app->user->isGuest) { ?>
          <li class="site-nav-item nav-item">
            <a class="signup-link<?php echo Util::getMenuActive($this, 'user/signup'); ?>" 
               href="<?php echo Url::to(['user/signup']); ?>"
               ><?php echo Yii::t('app', 'MENU_SIGNUP'); ?></a>
          </li>
          <li class="site-nav-item nav-item<?php echo Util::getMenuActive($this, 'user/login'); ?>">
            <a class="nav-link" 
               href="<?php echo Url::to(['user/login']); ?>"
               ><?php echo Yii::t('app', 'MENU_LOGIN'); ?></a>
          </li>
          <?php } else { ?>
          
              <li class="site-nav-item nav-item<?php echo Util::getMenuActive($this, 'user/account'); ?>">
                <a class="nav-link" 
                   href="<?php echo Url::to(['user/account']); ?>"
                   ><?php echo Yii::t('app', 'MENU_MY_ACCOUNT'); ?></a>
              </li>
          
              <li class="site-nav-item nav-item">
                  <?php echo Html::beginForm(['/user/logout'], 'post')
                      . Html::submitButton(
                          Yii::t('app', 'MENU_LOGOUT'),
                          ['class' => 'logout-link']
                      )
                      . Html::endForm(); ?>
              </li>
              
          <?php } ?>
          
          <li class="nav-item dropdown text-center">
              <a class="nav-link dropdown-toggle" 
                  href="#" 
                  id="navbarDropdown" 
                  role="button" 
                  data-toggle="dropdown" 
                  aria-haspopup="true" 
                  aria-expanded="false">
                  <?php echo Yii::t('app', 'MENU_LANGUAGE'); ?>
              </a>
              <div class="site-dropdown-menu dropdown-menu" aria-labelledby="navbarDropdown">
                  <a class="dropdown-item<?php echo Yii::$app->language === 'en' ? ' active' : '';  ?>"
                      href="/user/language/en"
                      ><?php echo Yii::t('app', 'MENU_LANGUAGE_EN'); ?></a>
                  <a class="dropdown-item<?php echo Yii::$app->language === 'lt' ? ' active' : '';  ?>"
                      href="/user/language/lt"
                      ><?php echo Yii::t('app', 'MENU_LANGUAGE_LT'); ?></a>
              </div>
          </li>
        </ul>
    </div>
  </div>
</nav>

<div class="container flex-grow-1 d-flex justify-content-center px-0 px-md-1 <?php 
    echo Util::isFullHeight($this) ? 'align-items-center' : 'align-items-start'; ?>">
    <?php
    if (!empty($this->params['breadcrumbs'])) {
        echo Breadcrumbs::widget([
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]);
    }
    echo Alert::widget();
    echo $content;
    ?>
</div>

<?php if (!Yii::$app->session->has('cookieConsent')) { ?>
  
  <div class="site-hide">
    <div :class="'site-cookie-info d-flex justify-content-center align-items-center px-2 px-md-0' + (showCookieConsent ? ' show' : '')">
      <span class="site-cookie-text flex-grow-1 py-sm-2 py-md-0"><?php echo Yii::t('app', 'COOKIE_MESSAGE'); ?><a 
        href="/site/privacy-policy" 
        class="btn-link" 
        target="_blank"><?php echo Yii::t('app', 'PRIVACY_POLICY_LINK'); ?></a></span>
      <div class="site-cookie-close btn btn-primary mb-2 mb-md-0 mt-1 mt-md-0 mx-3" v-on:click="cookieConsent"><?php echo Yii::t('app', 'BUTTON_OK'); ?></div>
    </div>
  </div>
    
<?php } ?>

</div>

<?php if (isset($this->params['vueFile'])) {
    $this->registerJsFile("@web/js/vue-{$this->params['vueFile']}.js", ['depends' => [AppAsset::className()]]); 
}
?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>