models/Category.php
<?php

namespace app\models;

use Yii;
use yii\db\ActiveRecord;
use yii\behaviors\TimestampBehavior;
use yii\web\NotFoundHttpException;
use app\models\User;
use yii\helpers\ArrayHelper;
use app\components\Util;

/**
 * This is the model class for table "category".
 *
 * @property integer $id
 * @property integer $user_id
 * @property string $name
 * @property integer $order
 * @property integer $created_at
 * @property integer $updated_at
 * @property User $user
 * @property Code $codes
 */
class Category extends ActiveRecord
{
     /** @const SCENARIO_CREATE Scenario type */
    const SCENARIO_CREATE = 'create';
    
     /** @const SCENARIO_EDIT Scenario type */
    const SCENARIO_UPDATE = 'update';
  
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'category';
    }

    /**
     * @inheritdoc
     */
    public function scenarios()
    {
        return [
            static::SCENARIO_CREATE => [
                'user_id',
                'name',
                'order',
                'created_at',
                'updated_at',
            ],
            self::SCENARIO_UPDATE => [
                'id',
                'user_id',
                'name',
                'order',
                'created_at',
                'updated_at',
            ],
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            // id
            ['id', 'integer', 'min' => 0],
            ['id', 'unique', 'on' => static::SCENARIO_CREATE],
            ['id', 'required', 'on' => static::SCENARIO_UPDATE],
            
            // user_id
            ['user_id', 'default', 
                'value' => Util::currentUserId(), 
                'on' => static::SCENARIO_CREATE
            ],
            ['user_id', 'required'],
            ['user_id', 'compare', 
                'compareValue' => Util::currentUserId(0), 
                'operator' => '==',
                'on' => static::SCENARIO_UPDATE,
                'message' => Yii::t('app', 'MODEL_INVALID_USER_ID'),
            ],
            ['user_id', 'integer', 'min' => 0],
            ['user_id', 'exist', 
                'targetClass' => User::className(), 
                'targetAttribute' => 'id',
                'on' => static::SCENARIO_UPDATE,
            ],
            
            // name
            ['name', 'filter', 'filter' => 'trim'],
            ['name', 'required'],
            ['name', 'uniqueForUser', 'params' => ['id' => Util::currentUserId()]],
            ['name', 'string', 'max' => 255],
            
            // keywords
            ['keywords', 'filter', 'filter' => 'trim'],
            ['keywords', 'string', 'max' => 255],
            
            // order
            ['order', 'required'],
            ['order', 'integer', 'min' => 1,'max' => 99],

            // created_at
            ['created_at', 'integer'],

            // updated_at
            ['updated_at', 'integer'],
        ];
    }
    
    /**
     * @inheritdoc
     */
    public function uniqueForUser($attribute, $params)
    {
        $categories = self::find()
            ->select(['id', 'name'])
            ->where(['user_id' => $params['id']])
            ->orderBy(['order' => SORT_ASC])
            ->asArray()
            ->all();
        
        foreach($categories as $category) {
            if ($this->{$attribute} == $category['name'] &&
                $this->id !== $category['id']
            ) {
                $this->addError($attribute, 
                    Yii::t('app', 'CATEGORY_NAME_EXISTS'));
                return;
            }
        }
    }
    
    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('app', 'CATEGORY_LABEL_ID'),
            'user_id' => Yii::t('app', 'CATEGORY_LABEL_USER_ID'),
            'name' => Yii::t('app', 'CATEGORY_LABEL_NAME'),
            'order' => Yii::t('app', 'CATEGORY_LABEL_ORDER'),
            'created_at' => Yii::t('app', 'CATEGORY_LABEL_CREATED_AT'),
            'updated_at' => Yii::t('app', 'CATEGORY_LABEL_UPDATED_AT'),
        ];
    }
    
    /**
     * Loads model
     * 
     * @return Category model 
     * @throws NotFoundHttpException
     */
    public static function loadModel($id)
    {
        $model = static::findOne($id);
        if (is_null($model)) {
            throw new NotFoundHttpException(Yii::t('app', 'MODEL_NOT_FOUND', 
                ['class' => basename(str_replace('\\', '/', static::class))])
            );
        }
        return $model;
    }
    
    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(User::className(), ['id' => 'user_id']);
    }
    
   /**
     * @return \yii\db\ActiveQuery
     */
    public function getCodes()
    {
        return $this->hasMany(
            Code::className(), ['id' => 'code_id']
        )->viaTable(CategoryCode::tableName(), ['category_id' => 'id']);
    }
    
    /**
     * Verifies if logged user owns this code
     * 
     * @return boolean
     */
    public function checkOwner()
    {
        return $this->user_id === Util::currentUserId();
    }
    
    /**
     * Returns demo category list
     * 
     * @return array
     */
    public static function getDemoList()
    {
        $categories = self::find()
            ->select(['id', 'name'])
            ->where(['user_id' => 1])
            ->orderBy(['order' => SORT_ASC])
            ->asArray()
            ->all();
        
        return ArrayHelper::map($categories, 'id', 'name');
    }
    
    /**
     * Change categories order values if there are duplicates
     */
    public static function reorder()
    {
        $categories = self::find()
            ->select(['id', 'order'])
            ->where(['user_id' => Util::currentUserId()])
            ->orderBy(['order' => SORT_ASC])
            ->asArray()
            ->all();
        
        if (count($categories) < 2) {
            return;
        }
        
        $gaps = false;
        for ($i = 0; $i < count($categories) - 1; $i++) {
            if ($categories[$i + 1]['order'] - $categories[$i]['order'] > 1) {
                $gaps = true;
                break;
            }
        }
        
        $list = ArrayHelper::map($categories, 'id', 'order');
        
        if (!$gaps && count($list) === count(array_unique($list))) {
            return;
        }
        
        $used = [];
        $order = 1;
        
        for ($i = 0; $i < count($categories); $i++) {        
            while (in_array($order, $used)) {
                $order++;
            }
        
            array_push($used, $order);
            
            $model = self::loadModel($categories[$i]['id']);
            $model->setScenario(self::SCENARIO_UPDATE);
            $model->order = $order;
            $model->save();
        }
    }
    
    /**
     * Change categories order values to insert new not duplicated order value
     */
    public function reorderForNew()
    {
        $categories = self::find()
            ->where(['user_id' => Util::currentUserId()])
            ->orderBy(['order' => SORT_ASC])
            ->asArray()
            ->all();
        
        if (count($categories) === 0) {
            return;
        }
        
        $i = 0;
        while ($i < count($categories) && 
            $categories[$i]['order'] !== $this->order
        ) {
            $i++;
        }
        
        if ($i === count($categories)) {
            $i = 0;
        }
        
        while ($i < count($categories)) {
            $model = self::loadModel($categories[$i]['id']);
            $model->setScenario(self::SCENARIO_UPDATE);
            $model->order = $model->order + 1;
            $model->save();
            $i++;
        }
    }
    
    /**
     * Removes category from codes and then deletes it
     * 
     * @return boolean if model was deleted
     */
    public function deleteModel()
    {
        CategoryCode::deleteAll(['category_id' => $this->id]);
        return $this->delete();
    }
    
    /**
     * Returns user category array with isAssigned field
     * 
     * @return array
     */
    public static function getUserCategories()
    {
        $data = Category::find()
            ->where(['user_id' => Yii::$app->user->identity->id])
            ->orderBy(['order' => SORT_ASC])
            ->asArray()->all();
       
        foreach($data as $key => $item) {
            $category = Category::loadModel($item['id']);
            $data[$key]['isAssigned'] = count($category->codes) !== 0;
        }
        
        return $data;
    }
}

controllers/CategoryController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use app\models\Category;
use yii\web\NotAcceptableHttpException;
use app\components\PhpMessageSource;
use app\models\UserLog;
use app\models\UserLogAction;
use app\components\Util;
use yii\widgets\ActiveForm;

class CategoryController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'list',
                            'create',
                            'update',
                            'update-order',
                            'remove',
                            'validate',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }
   
    /**
     * Displays code snippets page.
     *
     * @return Response|string
     */
    public function actionList()
    {
        Category::reorder();
        $model = new Category(['scenario' => Category::SCENARIO_CREATE]);
        
        $items = Category::getUserCategories();
        
        $myData = [
            'messages' => PhpMessageSource::getMessages('frontend'),
            'data' => $items,
        ];
        
        $myData = Util::stringifyCode($myData);        
        
        return $this->render('list', [
            'model' => $model,
            'myData' => $myData,
        ]);
    }
    
    /**
     * Creates category record
     *
     * @throws NotAcceptableHttpException
     * @return string json
     */
    public function actionCreate()
    {
        $post = Yii::$app->request->post();
        
        if (!Yii::$app->request->isPost || 
            !Yii::$app->request->isAjax ||
            !isset($post['Category'])
        ) {
            throw new NotAcceptableHttpException(
                Yii::t('app', 'BAD_POST_REQUEST'));
        }
      
        $model = new Category(['scenario' => Category::SCENARIO_CREATE]);
        $model->load($post);
        $model->user_id = Util::currentUserId();
        $model->reorderForNew();
        $result = $model->save();
        
        if ($result) {
            UserLog::create(UserLogAction::ACTION_CATEGORY_CREATE);
        }
        
        $items = Category::getUserCategories();
        
        $response = [
            'message' => $result ? 'success' : 'error',
            'items' => $items,
            'id' => $model->id,
        ];
        
        return json_encode($response);
    }
    
    /**
     * Updates category record
     *
     * @throws NotAcceptableHttpException
     * @return string json
     */
    public function actionUpdate()
    {
        $post = Yii::$app->request->post();
        
        if (!Yii::$app->request->isPost || 
            !Yii::$app->request->isAjax ||
            !isset($post['Category'])
        ) {
            throw new NotAcceptableHttpException(
                Yii::t('app', 'BAD_POST_REQUEST'));
        }
        
        $model = Category::loadModel($post['Category']['id']);
        
        if (!$model->checkOwner()) {
            throw new NotAcceptableHttpException(
                Yii::t('app', 'ERROR_WRONG_OWNER'));
        }
      
        $model->setScenario(Category::SCENARIO_UPDATE);
        $model->load($post);
        $result = $model->save();
        
        if ($result) {
            UserLog::create(UserLogAction::ACTION_CATEGORY_UPDATE);
        }
        
        $attributes = $model->attributes;
        $attributes['isAssigned'] = count($model->codes) !== 0;
        
        $response = [
            'message' => $result ? 'success' : 'error',
            'item' => $attributes,
        ];
        
        return json_encode($response);
    }
    
    /**
     * Removes code record
     *
     * @param integer $id Model id
     * @throws NotAcceptableHttpException
     * @return string json
     */
    public function actionRemove($id)
    {
        if (!Yii::$app->request->isPost || 
            !Yii::$app->request->isAjax
        ) {
            throw new NotAcceptableHttpException(
                Yii::t('app', 'BAD_POST_REQUEST'));
        }
      
        $model = Category::loadModel($id);
        
        if (!$model->checkOwner()) {
            throw new NotAcceptableHttpException(
                Yii::t('app', 'ERROR_WRONG_OWNER'));
        }
        
        $result = $model->deleteModel();
        
        if ($result) {
            UserLog::create(UserLogAction::ACTION_CATEGORY_DELETE);
        }
        
        return json_encode([
            'message' => $result ? 'success' : 'error',
        ]);
    }
    
    /**
     * Validates category record
     *
     * @throws NotAcceptableHttpException
     * @return string json
     */
    public function actionValidate()
    {
        $post = Yii::$app->request->post();
        
        if (!Yii::$app->request->isPost || 
            !Yii::$app->request->isAjax ||
            !isset($post['Category'])
        ) {
            throw new NotAcceptableHttpException(
                Yii::t('app', 'BAD_POST_REQUEST'));
        }
      
        $model = new Category(['scenario' => Category::SCENARIO_UPDATE]);
        $model->load($post);
        
        Yii::$app->response->format = Response::FORMAT_JSON;
        return ActiveForm::validate($model);
    }
}

views/category/list.php
<?php

/* @var yii\web\View $this */
/* @var string $myData */

use yii\bootstrap4\ActiveForm;
use yii\helpers\Url;
use yii\web\View;

$this->title = Yii::t('app', 'TITLE_CATEGORY');
$this->params['breadcrumbs'] = null;
$this->params['fullHeight'] = false;
$this->params['vueFile'] = 'category';
?>
<div id="vue-component" class="site-category">
    <div :class="[alertShow ? 'show' : '', 'site-alert-container']">
      <div :class="'site-alert alert alert-' + alertColor" role="alert">{{ alertText }}</div>
    </div>
    <div class="row justify-content-center">

        <!--Inputs row-->
        <div class="row w-100 justify-content-center">


            <!--Search inputs-->
            <div class="col-lg-3 mb-4 px-4 d-flex flex-column justify-content-end">

            </div>

            <!--Code editor inputs-->
            <div class="col-lg-8">

                <!--Code editor inputs container-->
                <div class="row w-100 mb-4 ml-1 pl-3">

                    <div class="col-lg-6">
                        <div class="text-center mt-4 mt-lg-5 mb-3">
                            <a href="/code/list"><i class="fa fa-reply mr-2" aria-hidden="true"
                                ></i><?php echo Yii::t('app', 'LINK_GO_BACK_TO_CODE'); ?></a>
                        </div>

                        <div class="form-group row mb-3 d-flex justify-content-center">

                            <label
                                for="search"
                                class="col-sm-2 col-form-label col-form-label-sm"
                            ><?php echo Yii::t('app', 'LABEL_SEARCH'); ?></label>
                            <div class="col-sm-7 category-search-container">
                              <input type="text"
                                  id="search"
                                  class="form-control form-control-sm"
                                  @input="onSearchCriteriaInput"
                                  v-model="search"
                                  data-container="body"
                                  data-toggle="popover"
                                  data-placement="top"
                                  data-content="<?php echo Yii::t('app', 'SEARCH_CRITERIA_INFO'); ?>"
                                  />

                              <div :class="'category-search-clear' + (search.length ? ' show' : '')"
                                @click="clearSearch"
                                >&times;</div>
                            </div>

                        </div>

                    </div>
                    <div class="col-lg-6 d-flex flex-column align-items-start mb-lg-2">
                        <div class="d-flex h-100 align-items-end mb-1">
                            <div>
                                <button type="button"
                                    title="<?php echo Yii::t('app', 'BUTTON_TITLE_CREATE_NEW'); ?>"
                                    class="btn btn-primary code-button mx-1 mb-0"
                                    @click="createNewItem"
                                ><i class="fa fa-plus" aria-hidden="true"></i></button>
                                <button type="button"
                                    title="<?php echo Yii::t('app', 'BUTTON_TITLE_EDIT'); ?>"
                                    :class="[ isSelected ? '' : 'disabled', 'btn btn-primary code-button mx-1 mb-0 category-edit-padding']"
                                    @click="editItem"
                                ><i class="fa fa-edit" aria-hidden="true"></i></button>
                                <button type="button"
                                    title="<?php echo Yii::t('app', 'BUTTON_TITLE_REMOVE'); ?>"
                                    :class="[ selected ? '' : 'disabled', 'btn btn-primary code-button mx-1 mb-0']"
                                    :aria-disabled="isSelected"
                                    @click="confirmRemove"
                                ><i class="fa fa-times" aria-hidden="true"></i></button>
                                <button type="button"
                                    title="<?php echo Yii::t('app', 'BUTTON_TITLE_SORT_DOWN'); ?>"
                                    :class="[ isSelected ? '' : 'disabled', 'btn btn-primary code-button mx-1 mb-0']"
                                    :aria-disabled="isSelected"
                                    @click="onSortDown"
                                ><i class="fa fa-chevron-circle-down" aria-hidden="true"></i></button>
                                <button type="button"
                                    title="<?php echo Yii::t('app', 'BUTTON_TITLE_SORT_UP'); ?>"
                                    :class="[ isSelected ? '' : 'disabled', 'btn btn-primary code-button mx-1 mb-0']"
                                    :aria-disabled="isSelected"
                                    @click="onSortUp"
                                ><i class="fa fa-chevron-circle-up" aria-hidden="true"></i></button>
                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>

        <!--Content row-->
        <div class="row w-100 justify-content-center">
            <!--Result list-->
            <div class="result-list col-lg-3">
                <ul class="list-group category-site-list-group">
                    <li
                        :class="[item.id === selected ? 'selected' : '', 'list-group-item result-item no-text-select']"
                        v-for="item in results"
                        @click="selectResult(item.id)"
                    >
                        <div class="site-item-data site-item-name">{{ item.name }}</div>
                        <div class="site-item-data site-item-updated d-flex align-items-center justify-content-end"
                            ><?php echo Yii::t('app', 'LABEL_UPDATED'); ?>: {{ item.updated | timeFilter }}</div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
    <div class="modal fade"
      id="myModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">{{ modalTitle }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <input type="text" class="site-modal-copy-input">
          <div class="modal-body" v-html="modalText"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal"
              @click="onNegativeModalAction">{{ modalCancelButton }}</button>
            <button type="button" class="btn btn-secondary" @click="onPositiveModalAction">{{ modalActionButton }}</button>
          </div>
        </div>
      </div>
    </div>
    <div class="modal fade"
      id="editModal"
      tabindex="-1"
      role="dialog"
      aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title">{{ modalTitle }}</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>

          <?php $form = ActiveForm::begin([
              'id' => 'edit-name-form',
              'enableAjaxValidation' => true,
              'validationUrl' => Url::to(['/category/validate']),
          ]); ?>

              <div class="d-flex justify-content-center mt-2">

                <?php echo $form->field($model, 'name', [
                    'enableAjaxValidation' => true,
                    'options' => [
                        'class' => 'form-group form-inline mb-0 custom-width',
                    ],
                    'inputOptions' => [
                        'v-model' => 'modalValue',
                        'v-on:keyup.enter' => 'onPositiveModalAction',
                        'autofocus' => true,
                    ],
                ])->label($model->attributeLabels()['name'],
                    ['class' => 'mr-3']); ?>

                <?php echo $form->field($model, 'id', [
                    'options' => [
                        'class' => 'form-group mb-0'
                    ],
                    'inputOptions' => [
                        'v-model' => 'modalId',
                    ],
                ])->hiddenInput()->label(false); ?>

              </div>


          <div class="modal-body"></div>
          <div class="modal-footer">
            <button type="button" class="btn btn-outline-secondary" data-dismiss="modal"
              @click="onNegativeModalAction">{{ modalCancelButton }}</button>
            <button type="button" class="btn btn-secondary" @click="onPositiveModalAction">{{ modalActionButton }}</button>
          </div>

          <?php ActiveForm::end(); ?>
        </div>
      </div>
    </div>
</div>
<?php
$this->registerJs("
    window.myData = JSON.parse(\"" . $myData . "\");"
, View::POS_BEGIN);