controllers/UserController.php
<?php

namespace app\controllers;

use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use yii\web\NotAcceptableHttpException;
use app\models\User;
use yii\bootstrap4\ActiveForm;
use app\models\UserLog;
use app\models\UserLogAction;
use app\components\PhpMessageSource;
use yii\helpers\Url;

class UserController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => [
                            'account',
                            'update-account',
                            'change-password',
                            'logout',
                            'verify-email',
                            'email-verification-form',
                            'send-verification-email',
                        ],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                    [
                        'actions' => [
                            'login',
                            'validate-email',
                            'signup',
                            'password-reset-request',
                            'password-reset-form',
                            'password-reset-post',
                        ],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => [
                            'error',
                            'language',
                        ],
                        'allow' => true,
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                    'password-reset-post' => ['post'],
                    'send-new-verification-email' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->redirect(['code/list']);
        }

        $model = new LoginForm;
        $post = Yii::$app->request->post();
        
        if ($model->load($post) && $model->login()) {
            UserLog::create(UserLogAction::ACTION_LOGIN);
            Yii::$app->user->identity->setAccountLanguage();
            return $this->redirect(['code/list']);
        }
        
        if (Yii::$app->request->isPost) {
            $model->password = '';
            
            $user = User::findByUsername($model->username);
            if ($user === null) {
                UserLog::create(UserLogAction::ACTION_LOGIN_FAIL_EMAIL);
            } else {
                UserLog::create(UserLogAction::ACTION_LOGIN_FAIL_PASSWORD, $user->id);
            }
        }
        
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        UserLog::create(UserLogAction::ACTION_LOGOUT);
        Yii::$app->user->logout();
        return $this->goHome();
    }

    /**
     * Displays signup view
     *
     * @return Response|string
     */
    public function actionSignup()
    {
        $model = new User(['scenario' => User::SCENARIO_SIGNUP]);
        
        $languageId = User::getLanguageId(Yii::$app->session->get('lang'));
        if (!is_null($languageId)) {
            $model->language = $languageId;
        }
        $post = Yii::$app->request->post();
        
        if ($model->load($post) && $model->validate()) {
            $model->create();
            UserLog::create(UserLogAction::ACTION_SIGNUP, $model->id);
            Yii::$app->session->setFlash(
                'messageSuccess', Yii::t('app', 'SIGNUP_SUCCESS_MESSAGE'));
            return $this->redirect('login');
        }
        
        $model->password = '';
        $model->passwordConfirm = '';
        $languageList = User::getMappedLanguages();
        
        return $this->render('signup', [
            'model' => $model,
            'languageList' => $languageList,
        ]);
    }
    
    /**
     * Returns json response with email validation errors
     *
     * @return string
     */
    public function actionValidateEmail()
    {
        $model = new User;
        $model->scenario = User::SCENARIO_VALIDATE_EMAIL;
        if (Yii::$app->request->isAjax && $model->load(Yii::$app->request->post())) {
            UserLog::create(UserLogAction::ACTION_SIGNUP_VALIDATE_EMAIL);
            Yii::$app->response->format = Response::FORMAT_JSON;
            return ActiveForm::validate($model);
        }
    }
   
    /**
     * Changes language and refreshes page.
     *
     * @param string $lang
     * @throws NotAcceptableHttpException
     * @return Response|string
     */
    public function actionLanguage($lang)
    {
        $languageId = User::getLanguageId($lang);
        if (is_null($languageId)) {
            throw new NotAcceptableHttpException(
                Yii::t('app', 'BAD_REQUEST_ARGUMENT'));
        }
        Yii::$app->session->set('lang', $lang);
        
        if (!Yii::$app->user->isGuest) {
            $user = Yii::$app->user->identity;
            $user->setScenario(User::SCENARIO_UPDATE);
            $user->language = $languageId;
            $user->save();
        }
        
        UserLog::create(UserLogAction::ACTION_CHANGE_LANGUAGE);
        
        return $this->redirect(Yii::$app->request->referrer);
    }
    
    /**
     * Password reset request view
     *
     * @params string|null $email
     * @throws NotAcceptableHttpException
     * @return Response|string
     */
    public function actionPasswordResetRequest($email = null)
    {
        $model = new User(['scenario' => User::SCENARIO_PASSWORD_RESET_REQUEST]);
        
        if (!Yii::$app->request->isPost) {
            $myData = [
                'messages' => PhpMessageSource::getMessages('frontend'),
                'email' => base64_decode($email),
            ];

            return $this->render('password-reset-request', [
                'model' => $model,
                'myData' => json_encode($myData),
            ]);
        }
        
        if (!Yii::$app->request->isAjax) {
            throw new NotAcceptableHttpException(
                Yii::t('app', 'BAD_POST_REQUEST'));
        }
        
        $post = Yii::$app->request->post();
        
        if ($model->load($post)) {
            $model->validate();
        }
        
        if ($model->hasErrors()) {
            return json_encode([
                'message' => 'error',
                'errors' => $model->firstErrors['email'],
            ]);
        }
        
        if ($model->sendRecoveryEmail()) {
            $user = User::findByUsername($model->email);
            UserLog::create(UserLogAction::ACTION_PASSWORD_RESET_REQUEST, $user->id);
            
            Yii::$app->session->setFlash('tokenSent',
                Yii::t('app', 'PASSWORD_REQUEST_SENT_TEXT'));
            return json_encode([
                'message' => 'success',
            ]);
        }
        
        return json_encode([
            'message' => 'error',
        ]);
    }
    
    /**
     * Checks password reset token and shows password change form
     *
     * @return Response|string
     */
    public function actionPasswordResetForm($token)
    {
        $model = User::findByToken('password_reset_token', $token, true);
        $expired = is_null($model) ? null : $model->isTokenExpired('password_reset_token');
        
        if ($expired === null) {
            Yii::$app->session->setFlash('errorMessage',
                Yii::t('app', 'ERROR_MESSAGE_INVALID_TOKEN'));
            return $this->redirect(['/site/message']);
        }
        
        if ($expired) {
            Yii::$app->session->setFlash('errorMessage',
                Yii::t('app', 'ERROR_MESSAGE_EXPIRED_TOKEN'));
            return $this->redirect(['/site/message']);
        }

        $model->setScenario(User::SCENARIO_SECURITY);
        $model->password_reset_token = Yii::$app->security
            ->generateRandomString();
        $model->save();
        
        $model->setScenario(User::SCENARIO_PASSWORD_RESET);
        
        $model->setAccountLanguage();
        
        return $this->render('password-reset', [
            'model' => $model,
            'key' => Yii::$app->security->maskToken($model->password_reset_token),
        ]);
    }

    /**
     * Password reset request view
     *
     * @return Response|string
     */
    public function actionPasswordResetPost()
    {        
        $post = Yii::$app->request->post();
        $token = Yii::$app->request->post('tag', '');
        
        $model = User::findByToken('password_reset_token', $token, true);
        
        if ($model === null) {
            Yii::$app->session->setFlash('errorMessage',
                Yii::t('app', 'INVALID_REQUEST'));
            return $this->redirect(['/site/message']);
        }
        
        $model->setScenario(User::SCENARIO_PASSWORD_RESET);
        $model->password_reset_token = null;
        
        if ($model->load($post) && $model->validate()) {

views/user/account-password.php
<?php

/* @var yii\web\View $this  */
/* @var app\models\User $model  */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

    $form = ActiveForm::begin([
      'id' => 'password-change-form',
      'layout' => ActiveForm::LAYOUT_HORIZONTAL,
      'enableClientScript' => false,
      'fieldConfig' => [
          'horizontalCssClasses' => [
              'label' => 'col-sm-4 pt-1 px-0',
              'offset' => 'offset-sm-3',
              'wrapper' => 'col-sm-7',
              'error' => '',
              'hint' => '',
          ],
      ],
    ]); ?>

      <?= $form->field($model, 'currentPassword', [
          'options' => [
              'class' => 'form-group row justify-content-center',
          ],
      ])->passwordInput([
          'v-model' => 'currentPassword',
          'autofocus' => true,
      ]) ?>

      <?= $form->field($model, 'password', [
          'options' => [
              'class' => 'form-group row justify-content-center',
          ],
      ])->passwordInput([
          'v-model' => 'newPassword',
      ])->label(Yii::t('app', 'USER_LABEL_NEW_PASSWORD')) ?>

      <?= $form->field($model, 'passwordConfirm', [
          'options' => [
              'class' => 'form-group row justify-content-center',
          ],
      ])->passwordInput([
          'v-model' => 'newPasswordConfirm',
      ])->label(Yii::t('app', 'USER_LABEL_CONFIRM_NEW_PASSWORD')) ?>

      <div class="form-group mt-45 mb-1 text-center">
        <?php echo Html::button(Html::tag(
            'span', null, [
            'class' => 'spinner-grow spinner-grow-sm site-hide mr-1',
            'v-show' => 'loadingPassword',
        ]) . Yii::t('app', 'BUTTON_CHANGE'), [
            'v-bind:class' => "'btn btn-primary button-width mx-2' + (loadingPassword ? ' disabled' : '')", 
            'name' => 'password-change-button',
            'v-bind:disabled' => 'loadingPassword',
            'v-on:click' => 'changePassword'
        ]) . Html::button(Yii::t('app', 'BUTTON_RESET'), [
            'class' => 'btn btn-secondary button-width mx-2',
            'v-on:click' => 'resetPasswordForm',
        ]) ?>
      </div>

    <?php ActiveForm::end(); ?>

views/user/account-profile.php
<?php

/* @var yii\web\View $this  */
/* @var app\models\User $model  */
/* @var array $languageList  */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;

    $form = ActiveForm::begin([
      'id' => 'profile-form',
      'layout' => ActiveForm::LAYOUT_HORIZONTAL,
      'enableClientScript' => false,
      'fieldConfig' => [
          'horizontalCssClasses' => [
              'label' => 'col-sm-3 pt-1',
              'offset' => 'offset-sm-3',
              'wrapper' => 'col-sm-7',
              'error' => '',
              'hint' => '',
          ],
      ],
    ]); ?>

      <?= $form->field($model, 'email', [
          'options' => [
              'class' => 'form-group row justify-content-center',
          ],
      ])->textInput([
          'v-model' => 'email',
          'autofocus' => true,
      ]) ?>

      <?= $form->field($model, 'name', [
          'options' => [
              'class' => 'form-group row justify-content-center',
          ],
      ])->textInput([
          'v-model' => 'name',
      ]) ?>

      <?php echo $form->field($model, 'language', [
          'options' => [
              'class' => 'form-group row justify-content-center',
          ],
      ])->dropDownList($languageList, [
          'v-model' => 'language',
      ]); ?>

      <div class="form-group mt-45 mb-1 text-center">
        <?php echo Html::button(Html::tag(
            'span', null, [
            'class' => 'spinner-grow spinner-grow-sm site-hide mr-1',
            'v-show' => 'loadingAccount',
        ]) . Yii::t('app', 'BUTTON_UPDATE'), [
            'v-bind:class' => "'btn btn-primary button-width mx-2' + (loadingAccount ? ' disabled' : '')", 
            'name' => 'profile-button',
            'v-bind:disabled' => 'loadingAccount',
            'v-on:click' => 'updateAccount',
        ]) . Html::button(Yii::t('app', 'BUTTON_RESET'), [
            'class' => 'btn btn-secondary button-width mx-2',
            'v-on:click' => 'resetAccountForm',
        ]) ?>
      </div>

    <?php ActiveForm::end(); ?>

views/user/account.php
<?php

/* @var yii\web\View $this  */
/* @var app\models\User $model  */
/* @var string $myData */
/* @var array $languageList */

use yii\web\View;

$this->title = Yii::t('app', 'TITLE_ACCOUNT');
$this->params['breadcrumbs'] = null;
$this->params['fullHeight'] = true;
$this->params['vueFile'] = 'account';
?>
<div id="vue-component" class="site-account" v-cloak>
    
    <div :class="[alertShow ? 'show' : '', 'site-alert-container site-account-alert-container']">
      <div :class="'site-alert alert alert-' + alertColor + (isDangerAlert ? ' alert-dismissible' : '')" 
        role="alert"><div v-html="alertText"></div><button 
          type="button" 
          class="close" 
          v-if="isDangerAlert"
          v-on:click="hideAlert" 
          aria-label="Close"
          ><span aria-hidden="true">&times;</span></button></div>
    </div>
    
    <div class="row w-100 justify-content-center">
        
        <div class="col-sm-12 col-md-10 col-lg-7">
          
          <div class="card">
            <div class="card-body pt-4 px-4">
            
              <ul class="nav nav-tabs" id="myTab" role="tablist">
                  
                <li class="nav-item">
                  <a class="site-tab-link nav-link active" 
                    id="home-tab" 
                    @click="hideAlert"
                    data-toggle="tab" 
                    href="#profile" 
                    role="tab" 
                    aria-controls="profile" 
                    aria-selected="true"><?php echo Yii::t('app', 'ACCOUNT_TAB_PROFILE'); ?></a>
                </li>
                <li class="nav-item">
                  <a class="site-tab-link nav-link" 
                    id="profile-tab" 
                    @click="hideAlert"
                    data-toggle="tab" 
                    href="#change-password" 
                    role="tab" 
                    aria-controls="profile" 
                    aria-selected="false"><?php echo Yii::t('app', 'ACCOUNT_TAB_CHANGE_PASSWORD'); ?></a>
                </li>
              </ul>
                
              <div class="tab-content row justify-content-center" id="myTabContent">
                  
                <div class="col-sm-12 col-md-9 tab-pane fade pt-5 pb-0 px-4 show active" id="profile" role="tabpanel" aria-labelledby="profile-tab">
                  
                    <?php echo Yii::$app->controller->renderPartial(
                        'account-profile', [
                            'model' => $model,
                            'languageList' => $languageList,
                        ]
                    ); ?>
                    
                </div>
                  
                <div class="col-sm-12 col-md-9 tab-pane fade pt-5 pb-0 px-4" id="change-password" role="tabpanel" aria-labelledby="change-password-tab">
                  
                    <?php echo Yii::$app->controller->renderPartial(
                        'account-password', [
                            'model' => $model,
                        ]
                    ); ?>
                    
                </div>
                  
              </div>
            
            </div>
          </div>
              
        </div>
    </div>
</div>
<?php
$this->registerJs("
    window.myData = JSON.parse(\"" . $myData . "\");"
, View::POS_BEGIN);

views/user/login.php
<?php

use yii\bootstrap\Html;
use yii\helpers\Url;
use app\components\Util;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model app\models\LoginForm */

$this->title = Yii::t('app', 'TITLE_LOGIN');
$this->params['breadcrumbs'] = null;
$this->params['fullHeight'] = true;
$this->params['vueFile'] = 'login';
?>
<div id="vue-component" class="site-login col-sm-10 col-md-8 col-lg-5 position-relative">
    <div class="card">
        <div class="card-body px-4">
            <h4 class="site-card-header card-title text-center mb-0 mb-sm-3 mt-0 mt-sm-1"
                ><?php echo Yii::t('app', 'TEXT_SIGNIN'); ?></h4>
            <hr class="mb-4">
            <form method="post" action="<?php echo Url::to([$this->context->route]); ?>">
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><?php echo Util::icon('user'); ?></span>
                     </div>
                    <input 
                        id="<?php echo Html::getInputId($model, 'username'); ?>" 
                        name="<?php echo Html::getInputName($model, 'username'); ?>" 
                        class="form-control<?php echo array_key_exists('username', $model->errors) ? ' is-invalid' : ''; ?>" 
                        value="<?php echo $model->username; ?>"
                        placeholder="<?php echo Yii::t('app', 'LOGIN_EMAIL_PLACEHOLDER'); ?>" 
                        type="text">
                    <?php if (isset($model->firstErrors['username']) && 0) { ?>
                    <div class="invalid-tooltip invalid-feedback" 
                        ><?php echo $model->firstErrors['username']; ?></div>
                    <?php } ?>
                </div>
            </div>
            <div class="form-group">
                <div class="input-group">
                    <div class="input-group-prepend">
                        <span class="input-group-text"><?php echo Util::icon('lock'); ?></span>
                    </div>
                    <input 
                        id="<?php echo Html::getInputId($model, 'password'); ?>" 
                        name="<?php echo Html::getInputName($model, 'password'); ?>" 
                        class="form-control<?php echo array_key_exists('password', $model->errors) ? ' is-invalid' : ''; ?>" 
                        placeholder="******" 
                        type="password">
                    <?php if (isset($model->firstErrors['password']) && 0) { ?>
                    <div class="invalid-tooltip invalid-feedback" 
                        ><?php echo $model->firstErrors['password']; ?></div>
                    <?php } ?>
                </div>
            </div>
            <?php echo Util::getCSRFField(); ?>
            <div class="form-group">
                <button type="submit" class="btn btn-primary btn-block" @click="onSubmit($event)"
                    ><?php echo Yii::t('app', 'BUTTON_LOGIN'); ?></button>
            </div>
                <p class="text-center my-0 mt-sm-4 mb-sm-2"><a href="<?php echo Url::to(['/user/password-reset-request']) ; ?>" 
                    class="btn-link forgot-password-link"
                    @click.prevent="onForgotPassword"
                    ><?php echo Yii::t('app', 'LINK_FORGOT_PASSWORD'); ?></a></p>
            </form>
        </div>
    </div>
    
    <?php if (!empty($model->errors)) { ?>
    <div :class="'site-alert-message alert alert-danger position-absolute mt-4 mx-3 absolute-margins' + (show ? ' show' : '')"  v-cloak>
        <ul class="login-error-list mb-0">
            <?php foreach($model->firstErrors as $error) {
                echo Html::tag('li', $error);
            } ?>
        </ul>
    </div>
    <?php } ?>
    
    <?php if (Yii::$app->session->hasFlash('messageSuccess')) { ?>
    <div :class="'site-alert-message alert alert-success position-absolute mt-4 mx-3 text-center absolute-margins' + (show ? ' show' : '')">
        <?php echo Yii::$app->session->getFlash('messageSuccess'); ?>
    </div>
    <?php } ?>
</div>

views/user/password-reset-request.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\User */
/* @var $myData string */

use yii\helpers\Html;
use yii\helpers\Url;
use yii\bootstrap4\ActiveForm;
use yii\web\View;

$this->title = Yii::t('app', 'TITLE_PASSWORD_RESET_REQUEST');
$this->params['breadcrumbs'] = false;
$this->params['fullHeight'] = true;
$this->params['vueFile'] = 'password-reset-request';
?>
<div id="vue-component" class="site-password-reset-request col-sm-10 col-md-8 col-lg-5 position-relative">
    
    <div class="card">
        <div class="card-body pt-3 px-4">
    
            <h4 class="site-card-header card-title text-center mb-0 mb-sm-3 mt-0 mt-sm-1"><?php 
                echo Html::encode($this->title); ?></h4>
            <hr class="mb-3 mb-sm-4">
            <p class="text-center"><?php echo Yii::t('app', 'PASSSWORD_RESET_REQUEST_TEXT'); ?></p>

            <?php $form = ActiveForm::begin([
                'id' => 'password-reset-request-form',
                'enableClientScript' => false,
            ]); ?>

                <?php echo $form->field($model, 'email', [
                    'options' => [
                        'class' => 'form-group mx-lg-5',
                    ],
                ])->textInput([
                    'v-model' => 'email',
                    'v-on:input' => 'emailInput',
                ])->label(false); ?>
            
                <div class="form-group mt-4 text-center" v-cloak>
                    
                    <?php echo Html::button(Html::tag(
                            'span', null, [
                                'class' => 'spinner-grow spinner-grow-sm site-hide',
                                'v-show' => 'loading',
                            ]) . ' ' . Yii::t('app', 'BUTTON_SEND'), [
                        'v-bind:class' => "'btn btn-primary button-width mx-2' + (loading ? ' disabled' : '')",
                        'name' => 'send-button',
                        'v-bind:disabled' => 'loading',
                        'v-on:click' => 'submit',
                    ]); ?>
                    
                    <?php echo Html::a(
                        Yii::t('app', 'BUTTON_BACK'), 
                        Url::to(['user/login']),
                        [
                            'class' => 'btn btn-secondary button-width mx-2', 
                        ]
                    ); ?>
                    
                </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
    
    <div class="site-hide">
      <div :class="(alertShow ? 'show ' : '') + 
          'site-alert-message alert alert-' + alertColor + ' position-absolute mt-4 mx-3 text-center absolute-margins'"
      >{{ alertText }}</div>
    </div>
        
</div>

<?php
$this->registerJs("
    window.myData = JSON.parse('" . $myData . "');"
, View::POS_BEGIN);

views/user/password-reset.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\User */
/* @var $key string */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\helpers\Url;

$this->title = Yii::t('app', 'TITLE_PASSWORD_RESET');
$this->params['breadcrumbs'] = false;
$this->params['fullHeight'] = true;
$this->params['vueFile'] = 'password-reset';
?>
<div id="vue-component" class="site-password-reset col-sm-10 col-md-8 col-lg-5">
    
    <div class="card">
        <div class="card-body pt-3 px-4">
    
            <h4 class="card-title text-center mb-0 mb-sm-3"><?php echo Html::encode($this->title); ?></h4>
            <hr class="mb-4">

            <?php $form = ActiveForm::begin([
                'id' => 'password-reset-form',
                'action' => Url::to(['/user/password-reset-post']),
                'layout' => ActiveForm::LAYOUT_DEFAULT,
            ]); ?>

                <?php echo $form->field($model, 'password')->passwordInput(); ?>
            
                <?php echo $form->field($model, 'passwordConfirm')->passwordInput(); ?>
            
                <?php echo Html::hiddenInput('tag', $key); ?>
            
                <div class="form-group mt-4 text-center">
                    
                    <?php echo Html::submitButton(Yii::t('app', 'BUTTON_CHANGE'), [
                        'class' => 'btn btn-primary button-width mx-2',
                        'name' => 'change-password-button'
                    ]); ?>
                    
                </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
        
</div>

views/user/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap4\ActiveForm */
/* @var $model app\models\User */
/* @var $languageList array */

use yii\helpers\Html;
use yii\bootstrap4\ActiveForm;
use yii\captcha\Captcha;
use yii\helpers\Url;

$this->title = Yii::t('app', 'TITLE_NEW_ACCOUNT');
$this->params['breadcrumbs'] = false;
$this->params['fullHeight'] = true;
$this->params['vueFile'] = 'signup';
?>
<div id="vue-component" class="site-new-account col-md-12 col-lg-8">
    
    <div class="card">
        <div class="card-body pt-3 px-4">
    
            <h4 class="site-card-header card-title text-center mb-0 mb-sm-3 mt-0 mt-sm-1"><?php 
              echo Html::encode($this->title); ?></h4>
            <hr class="mb-3 mb-sm-4">

            <?php $form = ActiveForm::begin([
                'id' => 'signup-form',
                'enableAjaxValidation' => false,
                'validationUrl' => Url::to(['/user/validate-email']),
            ]); ?>

                <div class="form-row">
                    
                    <div class="col-md-6 px-1 px-sm-3">
                        <?php echo $form->field($model, 'email', [
                            'enableAjaxValidation' => true,
                            'options' => [
                                'class' => 'form-group',
                            ],
                            'inputOptions' => [
                                'autofocus' => true,
                            ],
                        ]); ?>
                    </div>
                    
                    <div class="col-md-6 px-1 px-sm-3">
                        <?php echo $form->field($model, 'name'); ?>
                    </div>
                    
                </div>

                <div class="form-row">
                    
                    <div class="col-md-6 px-1 px-sm-3">
                        <?php echo $form->field($model, 'language')->dropDownList($languageList); ?>
                    </div>
                    
                    <div class="col-md-6 px-1 px-sm-3">
                    
                    </div>
                    
                </div>
            
                <div class="form-row">
                    
                    <div class="col-md-6 px-1 px-sm-3">
                        <?php echo $form->field($model, 'password')->passwordInput(); ?>
                    </div>
                    
                    <div class="col-md-6 px-1 px-sm-3">
                        <?php echo $form->field($model, 'passwordConfirm')->passwordInput(); ?>
                    </div>
                    
                </div>
            
                <div class="form-row">
                    
                    <div class="col-md-6 px-1 px-sm-3">
                        <?php echo $form->field($model, 'verifyCode')
                            ->widget(Captcha::className(), [
                                'template' => '<div class="row align-items-center justify-content-around"><div class="col-lg-4">{image}</div><div class="col-lg-7">{input}</div></div>',
                        ]); ?>
                    </div>
                    
                    <div class="col-md-6 px-1 px-sm-3">
                        
                    </div>
                    
                </div>
            
                <div class="form-group mt-3 mt-sm-4 mb-0 mb-sm-3 text-center">
                    <?php echo Html::button(Html::tag(
                        'span', null, [
                        'v-bind:class' => "'spinner-grow spinner-grow-sm site-hide mr-1' + (loading ? ' disabled' : '')",
                        'v-show' => 'loading',
                    ]) . Yii::t('app', 'BUTTON_SIGNUP'), [
                        'class' => 'btn btn-primary button-width mx-2', 
                        'name' => 'register-button',
                        'v-bind:disabled' => 'loading',
                        'v-on:click' => 'validateForm',
                    ]) . Html::button(Yii::t('app', 'BUTTON_RESET'), [
                        'class' => 'btn btn-secondary button-width mx-2',
                        'v-on:click' => 'resetForm',
                    ]) ?>
                </div>

            <?php ActiveForm::end(); ?>

        </div>
    </div>
        
</div>